/*
 * App URI: upgrade/sampleDm
 * Source Location: upgrade/sampleDm.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5980), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("upgrade/sampleDm", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			function onBtnAutoFillClick(e){

				var rawText = app.lookup("txaUserInput").value; 
				if (!rawText) return alert("분석할 텍스트를 입력해주세요.");

				var targetDataMap = app.lookup("dmOrder"); 
				var headers = targetDataMap.getHeaders(); 
				
				// 기준이 될 '오늘 날짜' 구하기 (프롬프트 본문이 아닌 변수로 빼둡니다)
				var today = new Date();
				var todayStr = today.getFullYear() + "-" + String(today.getMonth() + 1).padStart(2, '0') + "-" + String(today.getDate()).padStart(2, '0');
				
				var columnNames = []; 
				
				import("./google_ai.js").then(function(module) {
					var GoogleGenerativeAI = module.GoogleGenerativeAI;
					var SchemaType = module.SchemaType;
					var genAI = new GoogleGenerativeAI("AIzaSyCRnkJyO1YeyTuMIJnDdcBCNQc2VtgqreU");
					
					var dynamicProperties = {}; 
					
					// 🚀 [전문가 방식] 반복문을 돌면서 컬럼의 특성에 따라 '맞춤형 스키마'를 자동 생성합니다.
					for(var i = 0; i < headers.length; i++) {
						var header = headers[i];
						var colId = header.getName(); 
						var colInfo = header.getInfo() || colId; 
						
						// eXBuilder6 컬럼의 실제 데이터 타입 가져오기 ("string", "number" 등)
						var eXBuilderDataType = header.getDataType(); 
						
						// 1. 기본 타입 설정 (숫자형 컬럼이면 AI에게도 NUMBER로 강제)
						var schemaType = SchemaType.STRING;
						if(eXBuilderDataType === "number" || eXBuilderDataType === "decimal") {
							schemaType = SchemaType.NUMBER;
						}
						
						// 2. 날짜 컬럼 자동 감지 및 포맷팅 규칙 주입
						// 컬럼 ID에 'date', 'dt'가 포함되어 있으면 날짜 변환 규칙을 스키마 설명(Description)에 몰래 끼워 넣습니다.
						var extraRule = "";
						var lowerColId = colId.toLowerCase();
						if(lowerColId.indexOf("date") > -1 || lowerColId.indexOf("dt") > -1) {
							extraRule = " (단, 상대적인 날짜 표현은 기준일 [" + todayStr + "]을 바탕으로 계산하여 반드시 'YYYY-MM-DD' 형식으로 변환할 것)";
						}

						columnNames.push(colId);
						
						// 3. 거대한 프롬프트 대신, 컬럼별 설명(Description)에 규칙을 분산 배치!
						dynamicProperties[colId] = { 
							type: schemaType, 
							description: "'" + colInfo + "' 데이터 추출." + extraRule + + "' 입니다. 해당하는 내용이 없으면 null로 반환하세요."
						};
					}
					
					// 시스템 설정과 스키마 주입
					var model = genAI.getGenerativeModel({
						model: "gemini-2.5-flash",
						// systemInstruction: "너는 엔터프라이즈 데이터 추출 AI다. 주어진 스키마 규칙을 엄격히 준수해라.", (선택 사항)
						generationConfig: {
							temperature: 0,
							responseMimeType: "application/json",
							responseSchema: {
								type: SchemaType.OBJECT,
								properties: dynamicProperties,
								required: columnNames
							}
						}
					});

					// 💡 메인 프롬프트가 기가 막히게 짧고 단순해집니다. (유지보수 극대화)
					var prompt = "다음 텍스트에서 데이터를 추출해:\n\"" + rawText + "\"";
					
					return model.generateContent(prompt);

				}).then(function(result) {
					var extractedData = JSON.parse(result.response.text());
					console.log("AI 추출 완료:", extractedData);
					
					for(var i = 0; i < columnNames.length; i++) {
						var colName = columnNames[i];
						var extractedValue = extractedData[colName];
						
						if(extractedValue !== undefined && extractedValue !== null) {
							targetDataMap.setValue(colName, extractedValue);
						}
					}
					
					app.getContainer().redraw();
					alert("자동 완성이 완료되었습니다!");

				}).catch(function(error) {
					console.error("AI 연동 오류:", error);
				});
			}
			// End - User Script
			
			// Header
			var dataMap_1 = new cpr.data.DataMap("dmOrder");
			dataMap_1.parseData({
				"columns" : [
					{"name": "reqDate"},
					{"name": "clientName"},
					{"name": "itemName"},
					{"name": "orderCount"},
					{"name": "food"}
				]
			});
			app.register(dataMap_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "Button";
			if(typeof onBtnAutoFillClick == "function") {
				button_1.addEventListener("click", onBtnAutoFillClick);
			}
			container.addChild(button_1, {
				"top": "107px",
				"left": "787px",
				"width": "144px",
				"height": "40px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("txaUserInput");
			textArea_1.value = "영업팀입니다. 다음 주 수요일까지 카카오엔터프라이즈 측에 최신형 서버 랙 15대 발주 처리 부탁드립니다. 빠른 처리 요망.";
			container.addChild(textArea_1, {
				"top": "79px",
				"left": "112px",
				"width": "553px",
				"height": "137px"
			});
			
			var group_1 = new cpr.controls.Container();
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.horizontalSpacing = "10px";
			formLayout_1.verticalSpacing = "10px";
			formLayout_1.topMargin = "5px";
			formLayout_1.rightMargin = "5px";
			formLayout_1.bottomMargin = "5px";
			formLayout_1.leftMargin = "5px";
			formLayout_1.setColumns(["100px", "1fr"]);
			formLayout_1.setRows(["25px", "1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "reqDate";
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "food";
				container.addChild(output_2, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_3 = new cpr.controls.Output();
				output_3.bind("value").toDataMap(app.lookup("dmOrder"), "reqDate");
				container.addChild(output_3, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var output_4 = new cpr.controls.Output();
				output_4.bind("value").toDataMap(app.lookup("dmOrder"), "food");
				container.addChild(output_4, {
					"colIndex": 1,
					"rowIndex": 1
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "250px",
				"left": "112px",
				"width": "482px",
				"height": "175px"
			});
		}
	});
	app.title = "sampleDm";
	cpr.core.Platform.INSTANCE.register(app);
})();
