/*
 * App URI: upgrade/upGradeDm
 * Source Location: upgrade/upGradeDm.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5980), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("upgrade/upGradeDm", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			/*
			 * 🚀 DataMap 단건 버전: 공통 코드(Code) 자동 치환 적용판
			 */
			function onBtnAutoFillMapClick(e){

				var rawText = app.lookup("txaUserInput").value; 
				if (!rawText) return alert("분석할 텍스트를 입력해주세요.");

				var targetDataMap = app.lookup("dmOrder"); 
				var headers = targetDataMap.getHeaders(); 
				var columnNames = []; 
				
				import("../google_ai.js").then(function(module) {
					var GoogleGenerativeAI = module.GoogleGenerativeAI;
					var SchemaType = module.SchemaType;
					var genAI = new GoogleGenerativeAI("");
					var dynamicProperties = {}; 

					// 💡 [고도화 2] 화면에서 쓰는 공통 코드들을 미리 사전(Dictionary)처럼 정의합니다.
					// 실무에서는 app.lookup("dsDeptCode") 등에서 라벨/값을 뽑아와 조립하면 완벽합니다!
					var codeDictionaries = {
						"deptCode": "영업팀: DEPT_001, 인사팀: DEPT_002, IT팀: DEPT_003",
						"bankCode": "국민은행: KB_04, 신한은행: SH_05, 우리은행: WR_06"
					};
					
					for(var i = 0; i < headers.length; i++) {
						var header = headers[i];
						var colId = header.getName(); 
						var colInfo = header.getInfo() || colId; 
						
						var schemaType = (header.getDataType() === "number") ? SchemaType.NUMBER : SchemaType.STRING;
						
						// 💡 코드 맵핑 룰 주입: 이 컬럼이 공통 코드 대상이라면 AI에게 규칙을 강제합니다.
						var extraRule = "";
						if (codeDictionaries[colId]) {
							extraRule = " (🔥매우 중요: 반드시 다음 매핑을 참고하여 한글이 아닌 '코드값'으로만 반환할 것. [매핑: " + codeDictionaries[colId] + "])";
						}

						columnNames.push(colId);
						dynamicProperties[colId] = { 
							type: schemaType, 
							description: "'" + colInfo + "' 데이터 추출." + extraRule 
						};
					}
					
					var model = genAI.getGenerativeModel({
						model: "gemini-2.5-flash", 
						generationConfig: {
							temperature: 0,
							responseMimeType: "application/json",
							responseSchema: {
								type: SchemaType.OBJECT,
								properties: dynamicProperties,
								required: columnNames
							}
						}
					});

					var prompt = "다음 텍스트에서 데이터를 추출해:\n\"" + rawText + "\"";
					return model.generateContent(prompt);

				}).then(function(result) {
					var extractedData = JSON.parse(result.response.text());
					console.log("✅ 코드 치환 완료:", extractedData);
					
					for(var i = 0; i < columnNames.length; i++) {
						var colName = columnNames[i];
						if(extractedData[colName] != null) targetDataMap.setValue(colName, extractedData[colName]);
					}
					
					app.getContainer().redraw();
					alert("공통 코드 치환이 완료되었습니다!");
				});
			}
			// End - User Script
			
			// Header
			var dataMap_1 = new cpr.data.DataMap("dmOrder");
			dataMap_1.parseData({
				"columns" : [
					{"name": "reqDate"},
					{"name": "clientName"},
					{"name": "itemName"},
					{"name": "orderCount"},
					{"name": "food"}
				]
			});
			app.register(dataMap_1);
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023.984px)", "tablet");
			app.supportMedia("all and (max-width: 499.984px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var button_1 = new cpr.controls.Button();
			button_1.value = "Button";
			if(typeof onBtnAutoFillMapClick == "function") {
				button_1.addEventListener("click", onBtnAutoFillMapClick);
			}
			container.addChild(button_1, {
				"top": "107px",
				"left": "787px",
				"width": "144px",
				"height": "40px"
			});
			
			var textArea_1 = new cpr.controls.TextArea("txaUserInput");
			textArea_1.value = "영업팀입니다. 다음 주 수요일까지 카카오엔터프라이즈 측에 최신형 서버 랙 15대 발주 처리 부탁드립니다. 빠른 처리 요망.";
			container.addChild(textArea_1, {
				"top": "79px",
				"left": "112px",
				"width": "553px",
				"height": "137px"
			});
			
			var group_1 = new cpr.controls.Container();
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.horizontalSpacing = "10px";
			formLayout_1.verticalSpacing = "10px";
			formLayout_1.topMargin = "5px";
			formLayout_1.rightMargin = "5px";
			formLayout_1.bottomMargin = "5px";
			formLayout_1.leftMargin = "5px";
			formLayout_1.setColumns(["100px", "1fr"]);
			formLayout_1.setRows(["25px", "1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "reqDate";
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "food";
				container.addChild(output_2, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var output_3 = new cpr.controls.Output();
				output_3.bind("value").toDataMap(app.lookup("dmOrder"), "reqDate");
				container.addChild(output_3, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var output_4 = new cpr.controls.Output();
				output_4.bind("value").toDataMap(app.lookup("dmOrder"), "food");
				container.addChild(output_4, {
					"colIndex": 1,
					"rowIndex": 1
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "250px",
				"left": "112px",
				"width": "482px",
				"height": "175px"
			});
		}
	});
	app.title = "upGradeDm";
	cpr.core.Platform.INSTANCE.register(app);
})();
